blog/urls.py
from django.urls import path,include
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name="blog"

urlpatterns = [
    path('',blog_view,name="index"),
    path('<int:pid>',blog_single,name='single'),
    path('category/<str:cat_name>',blog_view,name='category'),
    path('tag/<str:tag_name>',blog_view,name='tag'),
    path('author/<str:author_username>',blog_view,name='author'),
    path('search/',blog_search,name='search'),
    path('test',test,name='test'),
    path('latest/feed/', LatestEntriesFeed()),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from website.sitemaps import StaticViewSitemap
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from django.contrib.auth import views as auth_views

sitemaps = {
    'static': StaticViewSitemap,
    'blog':BlogSitemap

}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls'),name='home'),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('sitemap.xml', sitemap,{'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/password_reset_complete.html'),
     name='password_reset_complete'),



]
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

website/urls.py
from django.urls import path
from website.views import *

app_name="website"


urlpatterns = [
    path('',index,name="index"),
    path('about/',about,name="about"),
    path('contact/',contact,name='contact'),
    path('newsletter/',newsletter_view,name='newsletter'),
   

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from accounts.models import Account

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=225)
    def __str__(self):
        return self.name

class Post(models.Model):
    image=models.ImageField(upload_to='blog/',default='blog/default.jpg')
    author=models.ForeignKey(Account,on_delete=models.SET_NULL,null=True)
    title=models.CharField(max_length=300)
    content=models.TextField()
    contact_views=models.IntegerField(default=0)
    status=models.BooleanField(default=False)
    login_require=models.BooleanField(default=False)
    published_date=models.DateTimeField(null=True)
    created_date=models.DateField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)
    category=models.ManyToManyField(Category)
    tags = TaggableManager()

    def __str__(self):
        return self.title
    class Meta:
        ordering=['created_date']
    def get_absolute_url(self):
        return reverse('blog:single',kwargs={'pid':self.id})
class comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    name=models.CharField(max_length=225)
    email=models.EmailField()
    subject=models.CharField(max_length=225,blank = True)
    message=models.TextField()
    created_date=models.DateField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)
    approved=models.BooleanField(default=False)
    def __str__(self):
        return self.name










   

    

blog/forms.py
from django import forms
from blog.models import comment

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = comment
        fields = ['post','name','email','subject','message']
        

blog/views.py
from django.shortcuts import get_object_or_404, render,redirect
from blog.models import Post,comment
from django.db.models import F
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from blog.forms import CommentForm
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect



def blog_view(request,**kwargs):
    posts=Post.objects.filter(status=1).order_by('-published_date')
    if kwargs.get('cat_name') != None:
        posts=posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_username') != None:
        posts=posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('tag_name') != None:
        posts=posts.filter(tags__name__in=[kwargs['tag_name']])


    posts=Paginator(posts,3)
    try:
        page_number=request.GET.get('page')
        posts=posts.get_page(page_number)
    except PageNotAnInteger:
        posts=posts.get_page(1)
    except EmptyPage:
        posts=posts.get_page(1)
    context ={'posts':posts}
    return render(request,'blog/blog-home.html',context)
def blog_single(request,pid):
    posts=Post.objects.filter(pk=pid).update(contact_views=F("contact_views")+1)
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,"your comment submited")
  
        else:
            messages.add_message(request,messages.ERROR,"your comment did'nt submited")
    if Post.objects.filter(pk=pid+1).exists():
            has_next=True
    else:
            has_next=False
    if Post.objects.filter(pk=pid-1).exists():
            has_previous=True
    else:
            has_previous=False
    form=CommentForm()
    next_pid=pid+1
    previous_pid=pid-1
    if not Post.login_require:
        comments=comment.objects.filter(post=pid,approved=True).order_by('-created_date')
        posts=get_object_or_404(Post,pk=pid,status=1)
        context={'post':posts,'pid':pid,'has_next':has_next,'has_previous':has_previous,'next_pid':next_pid,'previous_pid':previous_pid,'comments':comments,'form':form}
        return render(request,'blog/blog-single.html',context)
    else:
        return HttpResponseRedirect(reverse('accounts:login'))

def test(request):
    # posts=Post.objects.filter()
    posts=Post.objects.filter(status=1)
    context = {'post':posts}
    return render(request,'test.html',context)
def blog_category(request,cat_name):
    posts=Post.objects.filter(status=1)
    posts=Post.objects.filter(category__name=cat_name)
    context={'posts':posts}
    return render(request,'blog/blog-home.html',context)
def blog_search(request):
    posts=Post.objects.filter(status=1)
    if request.method == 'GET':
        if s:=request.GET.get('s'):
            posts=posts.filter(content__contains=s)
    context={'posts':posts}
    return render(request,'blog/blog-home.html',context)







    

templates/blog/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg'%}" alt=""></a>
</div>

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block body %}
			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							<h1 class="text-white">
								Dude You’re Getting
								a Telescope				
							</h1>	
							<p class="text-white">
								There is a moment in the life of any aspiring astronomer that it is time to buy that first
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">		
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
								        <span></span>								        
								        <p>Enjoy your social life together</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg'%}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
								        <span></span>								        
								        <p>Be a part of politics</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg'%}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Food</h4>
								        <span></span>
								        <p>Let the food be finished</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>												
					</div>
				</div>	
			</section>
			<!-- End top-category-widget Area -->
			
			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							{% for post in posts %}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{% for cat in post.category.all %}
										<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a>{% if not forloop.last %},{% endif %}</li>
										{% endfor %}
										

										
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"D M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.contact_views}}</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{% comments_count post.id %}</a> <span class="lnr lnr-bubble"></span></p>						
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image.url}}" alt="">
									</div>
									<a class="posts-title" href="{% url 'blog:single' pid=post.id %}"><h3>{{post.title}}</h3></a>
									<p class="excert">
										{{post.content|truncatewords:2}}

									</p>
									<a href="{% url 'blog:single' pid=post.id %}" class="primary-btn">View More</a>
								</div>
							</div>
							{% endfor %}														
		                    <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
								{% if posts.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
									{% for i in posts.paginator.page_range %}
									{% if posts.number == i %}
		                                <li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
										{% else %}
									<li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                                    {% endif %}
		                            {% endfor %}
									{% if posts.has_next %}
		                                <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
		                        </ul>
		                    </nav>
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								{% include 'blog/blog-search.html' %}
							    {% include 'blog/blog-writer.html' %}
								{% popularposts %}
								{% include 'blog/blog-ads.html' %}
								{% postcategory %}
                                {% include 'blog/blog-newsletter.html' %}
								{% include 'blog/blog-tags.html' %}
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
			{% endblock %}
			
			

templates/blog/blog-newsletter.html
{% load static %}
<div class="single-sidebar-widget newsletter-widget">
    <h4 class="newsletter-title">Newsletter</h4>
    <p>
        Here, I focus on a range of items and features that we use in life without
        giving them a second thought.
    </p>
    <div class="form-group d-flex flex-row">
        <div class="col-autos">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
                    </div>
                </div>
                <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email"
                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'">
            </div>
        </div>
        <a href="#" class="bbtns">Subcribe</a>
    </div>
    <p class="text-bottom">
        You can unsubscribe at any time
    </p>
</div>

templates/blog/blog-popular-post.html
{% load humanize %} 
{% load static %}
{% load blog_tags %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title"> popular posts</h4>
    <div class="popular-post-list">
    {% for post in posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
        </div>
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{{post.image.url}}" alt="">
            </div>
            <div class="details">
                <a href="{% url 'blog:single' pid=post.id %}">
                    <h6>{{post.title}}</h6>
                </a>
                <p>{{post.published_date|date:"d M Y"}}</p>
                <p>{{post.published_date| naturalday}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/blog/blog-post-category.html
{% load static %}
{% load blog_tags %}
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
    {% for name,count in categories.items %}
        <li>
            <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
                <p>{{name}}</p>
                <p>{{count}}</p>
    {% endfor %}
            </a>
          </li>
    </ul>
</div>

templates/blog/blog-search.html
{% load static %}
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:search' %}" method="get">
        <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''"
            onblur="this.placeholder = 'Search Posts'">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block body %}
<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{posts.title}}
				</h1>
				<p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a> <span
						class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span
						class="lnr lnr-arrow-right"></span> <a href="blog-single.html"> Blog Details Page</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->
<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src="{% static 'img/blog/feature-img1.jpg'%}" alt="">
						</div>
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in post.category.all %}
							<a href="#">{{ cat.name }}</a>{% if not forloop.last %},{% endif %}
							{% endfor %}

						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">Mark wiens</a> <span
									class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"D M Y"}}</a> 
								<span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.contact_views}}</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{comments|length}} Comments</a> <span
									class="lnr lnr-bubble"></span></p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-github"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{post.title}}</h3>
						<p class="excert">
						<p>{{post.content}}</p>

					</div>
				</div>
				<div class="navigation-area">
					<div class="row">
						{% if has_previous %}
						<div
							class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							<div class="thumb">
								<a href="#"><img class="img-fluid" src="{% static 'img/blog/prev.jpg'%}" alt=""></a>
							</div>
							<div class="arrow">
								<a href="{% url 'blog:single' pid=previous_pid %}"><span
										class="lnr text-white lnr-arrow-left"></span></a>
							</div>
							<div class="detials">
								<p>Prev Post</p>
								<a href="{% url 'blog:single' pid=previous_pid %}">
									<h4>Space The Final Frontier</h4>
								</a>
							</div>
						</div>{% endif %}
						{% if has_next %}
						<div
							class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							<div class="detials">
								<p>Next Post</p>
								<a href="#">
									<h4>Telescopes 101</h4>
								</a>
							</div>
							<div class="arrow">
								<a href="{% url 'blog:single' pid=next_pid %}"><span
										class="lnr text-white lnr-arrow-right"></span></a>
							</div>
							<div class="thumb">
								<a href="{% url 'blog:single' pid=next_pid %}"><img class="img-fluid"
										src="{% static 'img/blog/next.jpg'%}" alt=""></a>
							</div>
						</div>{% endif %}
					</div>
				</div>
				<div class="comments-area">
					<h4>{{comments|length}}Comments</h4>
					<div class="comment-list">
					{% for comment in comments %}
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c1.jpg'%}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">{{comment.name}}</a></h5>
									<p class="date">{{comment.created_date|date:"d M Y"}}</p>
									<p class="comment">
										{{comment.message}}
									</p>
								</div>
							</div>
						</div>
						{% empty %}
						<p>no comments has been received</p>
						{% endfor %}
					</div>
				</div>
				<div class="comment-form">
					<h4>Leave a Comment</h4>

					
				<form action="{% url 'blog:single' pid=post.id %}" method="post">
					{% csrf_token %}
					<input type="hidden" name="post" value={{post.id}}>
					{% if request.user.is_authenticated %}
					<input type="hidden" name="name" value= {{request.user.name}}>
					<input type="hidden" name="email" value= {{request.user.email}}>
                    {% else %}
					<div class="form-group form-inline">
						<div class="form-group col-lg-6 col-md-12 name">
							<input type="text" class="form-control" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Enter Name'">
						</div>
						<div class="form-group col-lg-6 col-md-12 email">
							<input type="email" class="form-control" name="email" placeholder="Enter email address"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
						</div>
					</div>
					{% endif %}
					<div class="form-group">
						<input type="text" class="form-control" name="subject" placeholder="Subject" onfocus="this.placeholder = ''"
							onblur="this.placeholder = 'Subject'">
					</div>
					<div class="form-group">
						<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''"
							onblur="this.placeholder = 'Messege'" required=""></textarea>
					</div>
					<button type="submit" class="primary-btn text-uppercase">Post Comment</button>
					</form>
				</div>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					{% include 'blog/blog-search.html' %}
					{% include 'blog/blog-writer.html' %}
					{% popularposts %}
					{% include 'blog/blog-ads.html' %}
					{% include 'blog/blog-post-category.html' %}
					{% include 'blog/blog-newsletter.html' %}
					{% include 'blog/blog-tags.html' %}
				</div>
			</div>
		</div>
	</div>
</section>








<!-- End post-content Area -->



<!-- start footer Area -->
<footer class="footer-area section-gap">
	<div class="container">

		<div class="row">
			<div class="col-lg-3  col-md-6 col-sm-6">
				<div class="single-footer-widget">
					<h6>About Agency</h6>
					<p>
						The world has become so fast paced that people don’t want to stand by reading a page of
						information, they would much rather look at a presentation and understand the message. It has
						come to a point
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<div class="single-footer-widget">
					<h6>Navigation Links</h6>
					<div class="row">
						<div class="col">
							<ul>
								<li><a href="#">Home</a></li>
								<li><a href="#">Feature</a></li>
								<li><a href="#">Services</a></li>
								<li><a href="#">Portfolio</a></li>
							</ul>
						</div>
						<div class="col">
							<ul>
								<li><a href="#">Team</a></li>
								<li><a href="#">Pricing</a></li>
								<li><a href="#">Blog</a></li>
								<li><a href="#">Contact</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-3  col-md-6 col-sm-6">
				<div class="single-footer-widget">
					<h6>Newsletter</h6>
					<p>
						For business professionals caught between high OEM price and mediocre print and graphic output.
					</p>
					<div id="mc_embed_signup">
						<form target="_blank"
							action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
							method="get" class="subscription relative">
							<div class="input-group d-flex flex-row">
								<input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''"
									onblur="this.placeholder = 'Email Address '" required="" type="email">
								<button class="btn bb-btn"><span class="lnr lnr-location"></span></button>
							</div>
							<div class="mt-10 info"></div>
						</form>
					</div>
				</div>
			</div>
			<div class="col-lg-3  col-md-6 col-sm-6">
				<div class="single-footer-widget mail-chimp">
					<h6 class="mb-20">InstaFeed</h6>
					<ul class="instafeed d-flex flex-wrap">
						<li><img src="{% static 'img/i1.jpg'%}" alt=""></li>
						<li><img src="{% static 'img/i2.jpg'%}" alt=""></li>
						<li><img src="{% static 'img/i3.jpg'%}" alt=""></li>
						<li><img src="{% static 'img/i4.jpg'%}" alt=""></li>
						<li><img src="{% static 'img/i5.jpg'%}" alt=""></li>
						<li><img src="{% static 'img/i6.jpg'%}" alt=""></li>
						<li><img src="{% static 'img/i7.jpg'%}" alt=""></li>
						<li><img src="{% static 'img/i8.jpg'%}" alt=""></li>
					</ul>
				</div>
			</div>
		</div>

		<div class="row footer-bottom d-flex justify-content-between align-items-center">
			<p class="col-lg-8 col-sm-12 footer-text m-0">
				<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				Copyright &copy;
				<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
				with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
					target="_blank">Colorlib</a>
				<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
			</p>
			<div class="col-lg-4 col-sm-12 footer-social">
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-behance"></i></a>
			</div>
		</div>
	</div>
</footer>
<!-- End footer Area -->
{% endblock %}

templates/blog/blog-tags.html
{% load static %}
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    
    <ul>
        {% for tag in post.tags.all %}
        <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
        {% endfor %}
    </ul>
    
</div>

templates/blog/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/user-info.png'%}" alt="">
    <a href="#">
        <h4>Charlie Barber</h4>
    </a>
    <p>
        Senior blog writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend
        money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
    </p>
</div>